services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    container_name: keepcode_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      - PHP_MEMORY_LIMIT=256M
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: keepcode_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./.nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    container_name: keepcode_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: keepcode
      MYSQL_USER: keepcoder
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge